### ISSUE TITLE
Cannot edit a xlsx file: An error occurred during the work with the document.

### ISSUE THREAD

**Issue by djibux** [ONLYOFFICE/DesktopEditors#2400]
### This issue is unique.

- [x] I have used the [search tool](https://github.com/ONLYOFFICE/DesktopEditors/issues?q=) and did not find an issue describing my bug.

### Operating System

Linux

### Architecture

x86_64

### Package Type

flatpak

### Version information

9.4.0

### Expected Behavior

I want to be able to edit my .xlsx files.
It worked fine with OnlyOffice up to 9.2.0.

### Actual Behavior

Since the latest updates (9.3.0 and 9.4.0), I can no longer work with some of my .xlsx files.
Those files are not very complex: a couple of tabs, basic formulas, a couple of named ranges, and a few vlookup.  Nothing too fancy.

When trying to edit some cells, the application displays the following error as soon as I click on the formula:
```
An error occurred during the work with the document. Use the 'Download as...' option to save a backup copy to your computer's hard drive.
```
No further edits are allowed on my file after getting the error.

### Reproduction Steps

I cannot share my files as they contain sensitive information, but, again, the formulas are not complex.  For example, I cannot edit a cell with the following formula `=50701,11+O7`, with O7 being a cell that I can edit!

I tried recreating the error from an empty file, but couldn’t reproduce the issue.

### Additional information

Here is the detailed error from DevTools:
```
sdk-all-min.js:992 changesError: Error: Uncaught TypeError: $a.DVa.yi is not a function
 Script: file:///app/bin/opt/onlyoffice/desktopeditors/editors/sdkjs/cell/sdk-all.js
 Line: 7030:333
 userAgent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 AscDesktopEditor/9.4.0.129 Safari/537.36
 platform: Linux x86_64
 isLoadFullApi: true
 isDocumentLoadComplete: true
 performance.memory: {"totalJSHeapSize":116000000,"usedJSHeapSize":97400000,"jsHeapSizeLimit":3760000000}
 StackTrace: TypeError: $a.DVa.yi is not a function
    at sdk-all.js:7030:333
    at Array.findIndex (<anonymous>)
    at kb.s$d (sdk-all.js:7030:259)
    at Y.dkd (sdk-all.js:9265:308)
    at sdk-all.js:9266:35
    at X.Nq (sdk-all.js:9307:189)
    at sdk-all.js:9265:403
    at D (sdk-all.js:8850:193)
    at Y.dkd (sdk-all.js:9265:378)
    at sdk-all.js:6968:235
sdk-all.js:7030 Uncaught TypeError: $a.DVa.yi is not a function
    at sdk-all.js:7030:333
    at Array.findIndex (<anonymous>)
    at kb.s$d (sdk-all.js:7030:259)
    at Y.dkd (sdk-all.js:9265:308)
    at sdk-all.js:9266:35
    at X.Nq (sdk-all.js:9307:189)
    at sdk-all.js:9265:403
    at D (sdk-all.js:8850:193)
    at Y.dkd (sdk-all.js:9265:378)
    at sdk-all.js:6968:235
```

Let me know how I can further help with de debugging.

**Comment by Dmitry-Kov** [comment]
Hi @djibux,

Thank you for the detailed report!

This is a known issue. The error appears when the editor parses a formula in a file that contains named ranges — it is a regression introduced in version 9.3.0.

Good news: the problem is already fixed, and the fix will be included in the next release. Please keep checking for updates.

Thank you again for helping us improve the editors!

**Comment by djibux** [comment]
Great, thanks. 
-- 
djib
